name: Ubuntu

on: [workflow_dispatch]

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Wait for connection
        uses: mxschmitt/action-tmate@v3
